---
# tasks file for authselect
- name: Manage user-nsswitch.conf
  template:
    src: "user-nsswitch.conf.j2"
    dest: "/etc/authselect/user-nsswitch.conf"
    mode: 0644
    owner: root
    group: root
  notify:
    - Update PAM with authselect

- name: Get current authselect config
  command: authselect current -r
  register: authselect_current_raw
  check_mode: no
  changed_when: false

- name: Compare current authselect profile and features with desired state
  set_fact:
    authselect_current_profile: "{{ authselect_current_raw.stdout.split()[0] }}"
    authselect_current_features: "{{ authselect_current_raw.stdout.split()[1:] }}"
  changed_when:
    - authselect_profile != authselect_current_profile
    - authselect_features|sort != authselect_current_features|sort
  notify:
    - Update PAM with authselect
